project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - projects/Tips.qmd
website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - href: projects/Tips.qmd
        text: Projects
        icon: pencil
      
format:
  html:
    theme: [cosmo, styles.scss]

